### ISSUE TITLE
Drop nocache

### ISSUE THREAD

**Issue by mcollina** [Fdawgs/fastify-disablecache#1]
I'd recommend dropping `nocache` as it's a fairly simple implementation, see https://github.com/helmetjs/nocache/blob/dba4c205867e77be4b55537b0844c7ea9ebc6c5a/index.ts#L9-L15. This would also be more performant as `res.setHeader()` is a known bottleneck (use `reply.header()` instead).

**Comment by Fdawgs** [comment]
Thanks for the feedback @mcollina, i'll take a look!

**Comment by Fdawgs** [comment]
@mcollina this has been implemented in v1.0.1 that i've just released, thanks again!
