### ISSUE TITLE
Just use `no-store`

### ISSUE THREAD

**Issue by Jxck** [Fdawgs/fastify-disablecache#131]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### API/app/plugin version

all

### Node.js version

all

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

Hi Team.

Recentry I rewrited https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control section which linked by README. under reviewing of HTTP experts (chair of HTTP working group).

I rewirted misunderstanding of "don't cache". just use `no-store`.

But if you have some evidence of `no-store` does not works as expected. I wanna seriously know the case.

(FYI: original implementation of helmetjs author also doesn't has evidence of realworld problem https://github.com/helmetjs/nocache/issues/19#issuecomment-724709395)

Below are my thought for this library. Any commnets are welcome.

---
from the point of standards view.

If you wanna "don't store this response to any caches", just add `no-store`.

```
Cache-Control: no-store, max-age=0, must-revalidate
```

in this line, `no-store` is most restrictive directives and others are ignored. just wast of bytes.
if implementation respect others, `max-age=0, must-revalidate` means "allow to store but revalidate after being stale", so it allows store to the cache.

```
Pragma: no-cache
```

`Pragma` is deprecated for now. and it's for Request header, not for Response.
https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#rfc.section.5.4

```
Expires: 0
```

Expire is ignored once Cache-Control exists. But if it works, it requires Date formatted value.
Once the value is invalid format, it's ignored. so 0 is valid for current spec. But I feel it's better to add valid date but past when you think it required (I don't think so).

So for now, below are reasonable.

```
Surrogate-Control: no-store
Cache-Control: no-store
```
(I don't think Surrogate-Control are required, because Cache-Control could cover it)

### Steps to Reproduce

N/A

**Comment by Fdawgs** [comment]
Hi @Jxck,

Working in the public health sector in the UK I have to ensure backwards compatibility as much as possible, because not everyone accessing sites and services is running the latest version of Chrome, Edge, or Firefox. We still have people using Internet Explorer 5, and we cannot exclude them from accessing web-based health services because of that.

In response to your questions regarding headers and their directives/values:

- `Pragma` is still supported because it was [used by Microsoft as a response header in old versions of IE](https://docs.microsoft.com/en-us/troubleshoot/developer/browsers/connectivity-navigation/how-to-prevent-caching#the-pragma-no-cache-header)
- `Expires` is still supported in order to disable caching for [old clients that adhered to the HTTP 1.0 spec](https://www.w3.org/Protocols/HTTP/1.0/spec.html#Expires), when `Cache-Control` was not a thing

**Comment by Jxck** [comment]
@Fdawgs Thanks for reply !

Oh it's much interesting if you have specific reason to do this. Yes backward compatible is important and service should allow various user.

> Working in the public health sector in the UK
That seems real usecase what I want. Could you share a URL for it ?

my interest here is once keep compatible with such a old browsers, it really works on every aspects ? for example is it possible to build html+css+js contents compatible for IE5? they only implements HTTP/1.0 which doesn't supports Host based virtual host , content-negotiation. Aslo it only supports TLS1.0 or SSL3.0 (maybe), It really could establish a connection in correct cipher suite, and CA certificate ? It doesn't cause a security incident? etc etc etc

In recently deployment, for example using Fastify ! its soooo hard to support http/1.0, tls/1.0, html4, js?? client. I wonder it doesn't work (event could not establish access). So I'm so interested in your work !

On the other hand, sometimes access.log shows phantom entry which shows unbelievable user-agent from phantom old client. its mystery of internet.
If you consider "old browser user exists" based on access logs, I recommend you to check such a client could really works on your site. If it doesn't, it already lost compatible for them, so adding backward caching headers are only waste of bytes.
(I don't know how can I install IE5 to recent machines, VM?)

**Comment by Fdawgs** [comment]
@Jxck, just to let you know I'm investigating using only no-store in this plugin.

You may also want to raise this in OWASP's repos:

**Comment by Fdawgs** [comment]
Okay, having done further testing, only using `no-store` is not feasible for backwards compatibility.
Internet Explorer [uses the `no-cache` directive](https://docs.microsoft.com/en-us/troubleshoot/developer/browsers/connectivity-navigation/how-to-prevent-caching) to prevent caching, not `no-store` as it should. `max-age=0, must-revalidate` functions the same as `no-cache` and stops caching for even older clients.

Also see https://blog.httpwatch.com/2008/10/15/two-important-differences-between-firefox-and-ie-caching/
