### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by Fdawgs** [Fdawgs/fastify-disablecache#195]
### Prerequisites

- [X] I have written a descriptive title
- [X] I have searched existing feature requests to ensure it has not already been proposed

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### Description

For posterity, TypeScript support should be added.
This will open this plugin up to more users.

**Comment by Fdawgs** [comment]
@uzlopak, I know you've been smashing adding `nodenext` support in the official Fastify repos, would you be able to offer any advice, please?

A lot of my Fastify plugins are incredibly simple ones, but would like to add TypeScript support, as the hospital I work at is [merging with a neighbouring NHS trust in April](https://yeovilhospital.co.uk/better-care-for-local-people-the-merger-of-yeovil-hospital-nhs-foundation-trust-with-somerset-nhs-foundation-trust/), so their developers can also adopt my plugins, APIs, and Fastify.

**Comment by Uzlopak** [comment]
I created a PR #196 and described some aspects
