### ISSUE TITLE
add must-revalidate to Cache-Control header

### ISSUE THREAD

**Issue by anthony-telljohann** [Fdawgs/fastify-disablecache#60]
**Is your feature request related to a problem? Please describe.**
Yes. When using `max-age=0` without `must-revalidate`, then the server may serve stale resource if the server is down or loses connectivity.

**Describe the solution you'd like**
Add `must-revalidate` to the `Cache-Control` header.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Fdawgs** [comment]
Thanks for the report @anthony-telljohann!
Just spotted the section in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#requiring_revalidation regarding this.

Will fix it promptly!
